{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "0d83e0d7_b8886cb9",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 7620
      },
      "writtenOn": "2021-08-31T17:48:08Z",
      "side": 1,
      "message": "Do we have a follow-up plan for adding a bot to test \"v8_use_external_startup_data \u003d false\" case so that such compilation error can be caught?\nMaybe we can add a TODO comment in this CL for such a task.",
      "revId": "1270301f3140280d73203665abe2d6bc9a5bd7fd",
      "serverId": "fca2d64a-0420-3532-b200-12848c95a47b"
    }
  ]
}